/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as TrackOrderRouteImport } from './routes/Track-Order'
import { Route as TermsChar38ConditionsRouteImport } from './routes/Terms&Conditions'
import { Route as SizeGuideRouteImport } from './routes/Size-Guide'
import { Route as ShippingDeliveryRouteImport } from './routes/Shipping-Delivery'
import { Route as ReturnPolicyRouteImport } from './routes/Return-Policy'
import { Route as RefundPolicyRouteImport } from './routes/Refund-Policy'
import { Route as PrivacyPolicyRouteImport } from './routes/Privacy-Policy'
import { Route as PaymentPolicyRouteImport } from './routes/Payment-Policy'
import { Route as FAQsRouteImport } from './routes/FAQs'
import { Route as CancellationPolicyRouteImport } from './routes/Cancellation-Policy'
import { Route as BulkOrderRouteImport } from './routes/Bulk-Order'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/Track-Order',
  path: '/Track-Order',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsChar38ConditionsRoute = TermsChar38ConditionsRouteImport.update({
  id: '/Terms&Conditions',
  path: '/Terms&Conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/Size-Guide',
  path: '/Size-Guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingDeliveryRoute = ShippingDeliveryRouteImport.update({
  id: '/Shipping-Delivery',
  path: '/Shipping-Delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnPolicyRoute = ReturnPolicyRouteImport.update({
  id: '/Return-Policy',
  path: '/Return-Policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/Refund-Policy',
  path: '/Refund-Policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/Privacy-Policy',
  path: '/Privacy-Policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPolicyRoute = PaymentPolicyRouteImport.update({
  id: '/Payment-Policy',
  path: '/Payment-Policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FAQsRoute = FAQsRouteImport.update({
  id: '/FAQs',
  path: '/FAQs',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/Cancellation-Policy',
  path: '/Cancellation-Policy',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkOrderRoute = BulkOrderRouteImport.update({
  id: '/Bulk-Order',
  path: '/Bulk-Order',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Bulk-Order': typeof BulkOrderRoute
  '/Cancellation-Policy': typeof CancellationPolicyRoute
  '/FAQs': typeof FAQsRoute
  '/Payment-Policy': typeof PaymentPolicyRoute
  '/Privacy-Policy': typeof PrivacyPolicyRoute
  '/Refund-Policy': typeof RefundPolicyRoute
  '/Return-Policy': typeof ReturnPolicyRoute
  '/Shipping-Delivery': typeof ShippingDeliveryRoute
  '/Size-Guide': typeof SizeGuideRoute
  '/Terms&Conditions': typeof TermsChar38ConditionsRoute
  '/Track-Order': typeof TrackOrderRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Bulk-Order': typeof BulkOrderRoute
  '/Cancellation-Policy': typeof CancellationPolicyRoute
  '/FAQs': typeof FAQsRoute
  '/Payment-Policy': typeof PaymentPolicyRoute
  '/Privacy-Policy': typeof PrivacyPolicyRoute
  '/Refund-Policy': typeof RefundPolicyRoute
  '/Return-Policy': typeof ReturnPolicyRoute
  '/Shipping-Delivery': typeof ShippingDeliveryRoute
  '/Size-Guide': typeof SizeGuideRoute
  '/Terms&Conditions': typeof TermsChar38ConditionsRoute
  '/Track-Order': typeof TrackOrderRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Bulk-Order': typeof BulkOrderRoute
  '/Cancellation-Policy': typeof CancellationPolicyRoute
  '/FAQs': typeof FAQsRoute
  '/Payment-Policy': typeof PaymentPolicyRoute
  '/Privacy-Policy': typeof PrivacyPolicyRoute
  '/Refund-Policy': typeof RefundPolicyRoute
  '/Return-Policy': typeof ReturnPolicyRoute
  '/Shipping-Delivery': typeof ShippingDeliveryRoute
  '/Size-Guide': typeof SizeGuideRoute
  '/Terms&Conditions': typeof TermsChar38ConditionsRoute
  '/Track-Order': typeof TrackOrderRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Bulk-Order'
    | '/Cancellation-Policy'
    | '/FAQs'
    | '/Payment-Policy'
    | '/Privacy-Policy'
    | '/Refund-Policy'
    | '/Return-Policy'
    | '/Shipping-Delivery'
    | '/Size-Guide'
    | '/Terms&Conditions'
    | '/Track-Order'
    | '/about'
    | '/cart'
    | '/contact'
    | '/shop'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Bulk-Order'
    | '/Cancellation-Policy'
    | '/FAQs'
    | '/Payment-Policy'
    | '/Privacy-Policy'
    | '/Refund-Policy'
    | '/Return-Policy'
    | '/Shipping-Delivery'
    | '/Size-Guide'
    | '/Terms&Conditions'
    | '/Track-Order'
    | '/about'
    | '/cart'
    | '/contact'
    | '/shop'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/Bulk-Order'
    | '/Cancellation-Policy'
    | '/FAQs'
    | '/Payment-Policy'
    | '/Privacy-Policy'
    | '/Refund-Policy'
    | '/Return-Policy'
    | '/Shipping-Delivery'
    | '/Size-Guide'
    | '/Terms&Conditions'
    | '/Track-Order'
    | '/about'
    | '/cart'
    | '/contact'
    | '/shop'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BulkOrderRoute: typeof BulkOrderRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  FAQsRoute: typeof FAQsRoute
  PaymentPolicyRoute: typeof PaymentPolicyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ReturnPolicyRoute: typeof ReturnPolicyRoute
  ShippingDeliveryRoute: typeof ShippingDeliveryRoute
  SizeGuideRoute: typeof SizeGuideRoute
  TermsChar38ConditionsRoute: typeof TermsChar38ConditionsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  ShopRoute: typeof ShopRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Track-Order': {
      id: '/Track-Order'
      path: '/Track-Order'
      fullPath: '/Track-Order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Terms&Conditions': {
      id: '/Terms&Conditions'
      path: '/Terms&Conditions'
      fullPath: '/Terms&Conditions'
      preLoaderRoute: typeof TermsChar38ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Size-Guide': {
      id: '/Size-Guide'
      path: '/Size-Guide'
      fullPath: '/Size-Guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Shipping-Delivery': {
      id: '/Shipping-Delivery'
      path: '/Shipping-Delivery'
      fullPath: '/Shipping-Delivery'
      preLoaderRoute: typeof ShippingDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Return-Policy': {
      id: '/Return-Policy'
      path: '/Return-Policy'
      fullPath: '/Return-Policy'
      preLoaderRoute: typeof ReturnPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Refund-Policy': {
      id: '/Refund-Policy'
      path: '/Refund-Policy'
      fullPath: '/Refund-Policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Privacy-Policy': {
      id: '/Privacy-Policy'
      path: '/Privacy-Policy'
      fullPath: '/Privacy-Policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Payment-Policy': {
      id: '/Payment-Policy'
      path: '/Payment-Policy'
      fullPath: '/Payment-Policy'
      preLoaderRoute: typeof PaymentPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/FAQs': {
      id: '/FAQs'
      path: '/FAQs'
      fullPath: '/FAQs'
      preLoaderRoute: typeof FAQsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Cancellation-Policy': {
      id: '/Cancellation-Policy'
      path: '/Cancellation-Policy'
      fullPath: '/Cancellation-Policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Bulk-Order': {
      id: '/Bulk-Order'
      path: '/Bulk-Order'
      fullPath: '/Bulk-Order'
      preLoaderRoute: typeof BulkOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BulkOrderRoute: BulkOrderRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  FAQsRoute: FAQsRoute,
  PaymentPolicyRoute: PaymentPolicyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ReturnPolicyRoute: ReturnPolicyRoute,
  ShippingDeliveryRoute: ShippingDeliveryRoute,
  SizeGuideRoute: SizeGuideRoute,
  TermsChar38ConditionsRoute: TermsChar38ConditionsRoute,
  TrackOrderRoute: TrackOrderRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  ShopRoute: ShopRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
