/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingDeliveryRouteImport } from './routes/shipping-delivery'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as ReturnPolicyRouteImport } from './routes/return-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PaymentPolicyRouteImport } from './routes/payment-policy'
import { Route as NewInRouteImport } from './routes/new-in'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as BulkOrderRouteImport } from './routes/bulk-order'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingDeliveryRoute = ShippingDeliveryRouteImport.update({
  id: '/shipping-delivery',
  path: '/shipping-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnPolicyRoute = ReturnPolicyRouteImport.update({
  id: '/return-policy',
  path: '/return-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPolicyRoute = PaymentPolicyRouteImport.update({
  id: '/payment-policy',
  path: '/payment-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewInRoute = NewInRouteImport.update({
  id: '/new-in',
  path: '/new-in',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkOrderRoute = BulkOrderRouteImport.update({
  id: '/bulk-order',
  path: '/bulk-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bulk-order': typeof BulkOrderRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/new-in': typeof NewInRoute
  '/payment-policy': typeof PaymentPolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/sale': typeof SaleRoute
  '/shipping-delivery': typeof ShippingDeliveryRoute
  '/shop': typeof ShopRoute
  '/size-guide': typeof SizeGuideRoute
  '/store': typeof StoreRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bulk-order': typeof BulkOrderRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/new-in': typeof NewInRoute
  '/payment-policy': typeof PaymentPolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/sale': typeof SaleRoute
  '/shipping-delivery': typeof ShippingDeliveryRoute
  '/shop': typeof ShopRoute
  '/size-guide': typeof SizeGuideRoute
  '/store': typeof StoreRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bulk-order': typeof BulkOrderRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/new-in': typeof NewInRoute
  '/payment-policy': typeof PaymentPolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/sale': typeof SaleRoute
  '/shipping-delivery': typeof ShippingDeliveryRoute
  '/shop': typeof ShopRoute
  '/size-guide': typeof SizeGuideRoute
  '/store': typeof StoreRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bulk-order'
    | '/cancellation-policy'
    | '/cart'
    | '/collections'
    | '/contact'
    | '/faqs'
    | '/new-in'
    | '/payment-policy'
    | '/privacy-policy'
    | '/refund-policy'
    | '/return-policy'
    | '/sale'
    | '/shipping-delivery'
    | '/shop'
    | '/size-guide'
    | '/store'
    | '/terms-and-conditions'
    | '/track-order'
    | '/wishlist'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bulk-order'
    | '/cancellation-policy'
    | '/cart'
    | '/collections'
    | '/contact'
    | '/faqs'
    | '/new-in'
    | '/payment-policy'
    | '/privacy-policy'
    | '/refund-policy'
    | '/return-policy'
    | '/sale'
    | '/shipping-delivery'
    | '/shop'
    | '/size-guide'
    | '/store'
    | '/terms-and-conditions'
    | '/track-order'
    | '/wishlist'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bulk-order'
    | '/cancellation-policy'
    | '/cart'
    | '/collections'
    | '/contact'
    | '/faqs'
    | '/new-in'
    | '/payment-policy'
    | '/privacy-policy'
    | '/refund-policy'
    | '/return-policy'
    | '/sale'
    | '/shipping-delivery'
    | '/shop'
    | '/size-guide'
    | '/store'
    | '/terms-and-conditions'
    | '/track-order'
    | '/wishlist'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BulkOrderRoute: typeof BulkOrderRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  CartRoute: typeof CartRoute
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  NewInRoute: typeof NewInRoute
  PaymentPolicyRoute: typeof PaymentPolicyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ReturnPolicyRoute: typeof ReturnPolicyRoute
  SaleRoute: typeof SaleRoute
  ShippingDeliveryRoute: typeof ShippingDeliveryRoute
  ShopRoute: typeof ShopRoute
  SizeGuideRoute: typeof SizeGuideRoute
  StoreRoute: typeof StoreRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WishlistRoute: typeof WishlistRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-delivery': {
      id: '/shipping-delivery'
      path: '/shipping-delivery'
      fullPath: '/shipping-delivery'
      preLoaderRoute: typeof ShippingDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-policy': {
      id: '/return-policy'
      path: '/return-policy'
      fullPath: '/return-policy'
      preLoaderRoute: typeof ReturnPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-policy': {
      id: '/payment-policy'
      path: '/payment-policy'
      fullPath: '/payment-policy'
      preLoaderRoute: typeof PaymentPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-in': {
      id: '/new-in'
      path: '/new-in'
      fullPath: '/new-in'
      preLoaderRoute: typeof NewInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-order': {
      id: '/bulk-order'
      path: '/bulk-order'
      fullPath: '/bulk-order'
      preLoaderRoute: typeof BulkOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BulkOrderRoute: BulkOrderRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  CartRoute: CartRoute,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  NewInRoute: NewInRoute,
  PaymentPolicyRoute: PaymentPolicyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ReturnPolicyRoute: ReturnPolicyRoute,
  SaleRoute: SaleRoute,
  ShippingDeliveryRoute: ShippingDeliveryRoute,
  ShopRoute: ShopRoute,
  SizeGuideRoute: SizeGuideRoute,
  StoreRoute: StoreRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TrackOrderRoute: TrackOrderRoute,
  WishlistRoute: WishlistRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
